[package]
name = "pdex"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
rusqlite = { version = "0.33.0", features = ["bundled"] }
