[package]
name = "pdex"
version = "0.1.4"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
indexmap = "2.7.1"
rusqlite = { version = "0.33.0", features = ["bundled"] }
